{{- if and (or (eq .Values.mode "statefulset") (and .Values.targetAllocator.enabled (eq .Values.targetAllocator.collectionMode "statefulset"))) (.Values.configMap.create) -}}
{{- if and .Values.targetAllocator.enabled (eq .Values.targetAllocator.collectionMode "statefulset") .Values.presets.ebpfProfiler.enabled }}
{{- fail "[ERROR] targetAllocator.collectionMode: statefulset does not support presets.ebpfProfiler.enabled: true." }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-statefulset
  namespace: {{ template "opentelemetry-collector.namespace" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  relay: |
    {{- $poolData := deepCopy . | mergeOverwrite (dict "isTargetAllocatorPool" true) -}}
    {{- include "opentelemetry-collector.deploymentConfig" $poolData | nindent 4 -}}
{{- end }}
