{{- if .Values.collectorCRD.generate -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector.serviceAccountName" . }}-targetallocator
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
{{ end }}
