{{- if and (.Values.targetAllocator.enabled) (not (.Values.targetAllocator.serviceAccount)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector.serviceAccountName" . }}-targetallocator
  namespace: {{ template "opentelemetry-collector.namespace" . }}
  labels:
    {{- include "opentelemetry-target-allocator.labels" . | nindent 4 }}
{{ end }}
