mode: daemonset

presets:
  kubeletMetrics:
    enabled: true
  spanMetrics:
    enabled: true
    transformStatements:
      - set(attributes["http.response.status_code"], attributes["http.status_code"]) where attributes["http.response.status_code"] == nil
    dbMetrics:
      enabled: false

config:
  exporters:
    otlp:
      endpoint: example-opentelemetry-collector:4317
      tls:
        insecure: true
  service:
    pipelines:
      logs:
        exporters:
         - otlp
         - debug
      metrics:
        exporters:
         - otlp
         - debug
      traces:
        exporters:
         - otlp
         - debug

resources:
  limits:
    cpu: 100m
    memory: 200M

