apiVersion: v2
name: opentelemetry-collector
version: 0.108.0
description: OpenTelemetry Collector Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/coralogix/opentelemetry-helm-charts
  - https://github.com/open-telemetry/opentelemetry-collector
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
  - https://github.com/open-telemetry/opentelemetry-helm-charts
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
  - name: povilasv
appVersion: 0.120.0
dependencies:
  - name: opentelemetry-ebpf-profiler
    version: 0.108.0
    condition: opentelemetry-ebpf-profiler.enabled
    repository: "file://../opentelemetry-ebpf-profiler"
