mode: daemonset
collectorCRD:
  generate: true

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    storeCheckpoints: true
  hostMetrics:
    enabled: true
configMap:
  create: false

serviceAccount:
  create: false

priorityClassName: "ds-priority"
nodeSelector:
  kubernetes.io/arch: "arm64"

resources:
  limits:
    cpu: 100m
    memory: 200M
