mode: daemonset

presets:
  ebpfProfiler:
    enabled: true
    samplesPerSecond: 77
  otlpExporter:
    enabled: false
  otlpReceiver:
    enabled: false
  # unsupported by ebpf profiler distro
  collectorMetrics:
    enabled: false

config:
  service:
    telemetry:
      resource:
        service.name: "opentelemetry-collector"
        cx.agent.type: "ebpf-profiler"
      logs:
        level: "debug"
