presets:
  profilesCollection:
    enabled: true
  metadata:
    enabled: true
    clusterName: "production"
    integrationName: "coralogix-integration-helm"

command:
  extraArgs: ["--feature-gates=+service.profilesSupport"]

resources:
  limits:
    cpu: 100m
    memory: 200M
