global:
  test: templated-value

mode: deployment
resources:
  limits:
    cpu: 100m
    memory: 200M

# Test the extra* parameters are build correctly
extraEnvsMap:
  TEST:
    value: "test"

extraVolumesMap:
  testpath:
    hostPath:
      path: /etc/hosts

extraVolumeMountsMap:
  testpath:
    mountPath: /etc/hosts
    mountPropagation: HostToContainer
    readOnly: true

# Tests `tpl` function reference used in pod labels and
# ingress.hosts[*]
podLabels:
  testLabel: "{{ .Values.global.test }}"

ingress:
  enabled: true
  hosts:
    - host: "{{ .Values.global.test }}"
      paths:
        - path: /
          pathType: Prefix
          port: 4318
