mode: daemonset

presets:
  jaegerReceiver:
    enabled: true
  zipkinReceiver:
    enabled: true
  kubernetesAttributes:
    enabled: true
  resourceDetection:
    enabled: true
  kubeletMetrics:
    enabled: true
  batch:
    enabled: true

resources:
  limits:
    cpu: 100m
    memory: 200M
