mode: daemonset

image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"

command:
  name: "otelcol-k8s"

podAnnotations:
  io.opentelemetry.discovery.logs/enabled: "false"

presets:
  annotationDiscovery:
    logs:
      enabled: true
    metrics:
      enabled: true

resources:
  limits:
    cpu: 100m
    memory: 200M
