mode: daemonset

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    extraFilelogOperators:
    - type: recombine
      combine_field: body
      source_identifier: attributes["log.file.path"]
      is_first_entry: body matches "^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}|[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})"
    multilineConfigs:
    - namespaceName:
        value: kube-system
      podName:
        value: app-.*
        useRegex: true
      containerName:
        value: http
      firstEntryRegex: ^[^\s].*
      combineWith: ""
    - namespaceName:
        value: default
      podName:
        value: app-.*
        useRegex: true
      firstEntryRegex: ^[^\s].*
      combineWith: ""
    - namespaceName:
        value: test
      firstEntryRegex: ^[^\s].*
      combineWith: ""

  mysql:
    metrics:
      enabled: true
      instances:
      - username: "root"
        password: ${env:MYSQL_PASSWORD}
        collectionInterval: 30s
        port: 3306
        labelSelectors:
            env: "test"
            team: "teamA"
  spanMetrics:
    enabled: true
    dbMetrics:
      enabled: true
      transformStatements:
        - set(attributes["db.namespace"], attributes["db.name"]) where attributes["db.namespace"] == nil
        - set(attributes["db.namespace"], attributes["server.address"]) where attributes["db.namespace"] == nil
        - set(attributes["db.namespace"], attributes["network.peer.name"]) where attributes["db.namespace"] == nil
        - set(attributes["db.namespace"], attributes["net.peer.name"]) where attributes["db.namespace"] == nil
        - set(attributes["db.namespace"], attributes["db.system"]) where attributes["db.namespace"] == nil
        - set(attributes["db.operation.name"], attributes["db.operation"]) where attributes["db.operation.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.sql.table"]) where attributes["db.collection_name"] == nil
        - set(attributes["db.collection_name"], attributes["db.cassandra.table"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.mongodb.collection"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.redis.database_index"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.elasticsearch.path_parts.index"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.cosmosdb.container"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["aws_dynamodb.table_names"]) where attributes["db.collection.name"] == nil
    collectionInterval: 30s
    metricsExpiration: 5m
    histogramBuckets: [1ms, 1s, 10s]
    spanNameReplacePattern:
    - regex: "^(.*)$"
      replacement: "$$1"
  kubernetesAttributes:
     enabled: true
  reduceResourceAttributes:
     enabled: true
