mode: daemonset

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    extraFilelogOperators:
    - type: recombine
      combine_field: body
      source_identifier: attributes["log.file.path"]
      is_first_entry: body matches "^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}|[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})"
  mysql:
    metrics:
      enabled: true
      instances:
      - username: "root"
        password: ${env:MYSQL_PASSWORD}
        port: 3306
        labelSelectors:
            env: "test"
            team: "teamA"
  spanMetrics:
    enabled: true
    spanNameReplacePattern:
      regex: "^(.*)$"
      replacement: "$1"

