mode: daemonset

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    extraFilelogOperators:
    - type: recombine
      combine_field: body
      source_identifier: attributes["log.file.path"]
      is_first_entry: body matches "^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}|[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})"
    multilineConfigs:
    - namespaceName:
        value: kube-system
      podName:
        value: app-.*
        useRegex: true
      containerName:
        value: http
      firstEntryRegex: ^[^\s].*
      combineWith: ""
    - namespaceName:
        value: default
      podName:
        value: app-.*
        useRegex: true
      firstEntryRegex: ^[^\s].*
      combineWith: ""
    - namespaceName:
        value: test
      firstEntryRegex: ^[^\s].*
      combineWith: ""

  mysql:
    metrics:
      enabled: true
      instances:
      - username: "root"
        password: ${env:MYSQL_PASSWORD}
        collectionInterval: 30s
        port: 3306
        labelSelectors:
            env: "test"
            team: "teamA"
  spanMetrics:
    enabled: true
    collectionInterval: 30s
    histogramBuckets: [1ms, 1s, 10s]
    spanNameReplacePattern:
    - regex: "^(.*)$"
      replacement: "$1"

