mode: daemonset
extraVolumes:
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id

extraVolumeMounts:
  - mountPath: /etc/machine-id
    mountPropagation: HostToContainer
    name: etcmachineid
    readOnly: true

config:
  exporters:
    coralogix:
      application_name: 'otel'
      domain: 'coralogix.com'

presets:
  k8sResourceAttributes:
    enabled: true
  batch:
    enabled: true
  collectorMetrics:
    enabled: false
  jaegerReceiver:
    enabled: true
  zipkinReceiver:
    enabled: true
  otlpReceiver:
    enabled: true
  resourceDetection:
    enabled: true
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    extraFilelogOperators:
    - type: recombine
      combine_field: body
      source_identifier: attributes["log.file.path"]
      is_first_entry: body matches "^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}|[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})"
    multilineConfigs:
    - namespaceName:
        value: kube-system
      podName:
        value: app-.*
        useRegex: true
      containerName:
        value: http
      firstEntryRegex: ^[^\s].*
      combineWith: ""
    - namespaceName:
        value: default
      podName:
        value: app-.*
        useRegex: true
      firstEntryRegex: ^[^\s].*
      combineWith: ""
    - namespaceName:
        value: test
      firstEntryRegex: ^[^\s].*
      combineWith: ""
  mysql:
    metrics:
      enabled: true
      instances:
      - username: "root"
        password: ${env:MYSQL_PASSWORD}
        collectionInterval: 30s
        port: 3306
        labelSelectors:
            env: "test"
            team: "teamA"
  headSampling:
    enabled: true

  spanMetrics:
    enabled: true
    transformStatements:
      - set(attributes["http.response.status_code"], attributes["http.status_code"]) where attributes["http.response.status_code"] == nil
    dbMetrics:
      enabled: true
      extraDimensions:
        - name: cgx.transaction
        - name: cgx.transaction.root
      transformStatements:
        - set(attributes["db.namespace"], attributes["db.name"]) where attributes["db.namespace"] == nil
        - set(attributes["db.namespace"], attributes["server.address"]) where attributes["db.namespace"] == nil
        - set(attributes["db.namespace"], attributes["network.peer.name"]) where attributes["db.namespace"] == nil
        - set(attributes["db.namespace"], attributes["net.peer.name"]) where attributes["db.namespace"] == nil
        - set(attributes["db.namespace"], attributes["db.system"]) where attributes["db.namespace"] == nil
        - set(attributes["db.operation.name"], attributes["db.operation"]) where attributes["db.operation.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.sql.table"]) where attributes["db.collection_name"] == nil
        - set(attributes["db.collection_name"], attributes["db.cassandra.table"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.mongodb.collection"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.redis.database_index"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.elasticsearch.path_parts.index"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["db.cosmosdb.container"]) where attributes["db.collection.name"] == nil
        - set(attributes["db.collection_name"], attributes["aws_dynamodb.table_names"]) where attributes["db.collection.name"] == nil
    compactMetrics:
      enabled: true
    errorTracking:
      enabled: true
    collectionInterval: 30s
    metricsExpiration: 5m
    aggregationCardinalityLimit: 100
    histogramBuckets: [1ms, 1s, 10s]
    spanNameReplacePattern:
    - regex: "^(.*)$"
      replacement: "$$1"
  kubernetesAttributes:
    enabled: true
  reduceResourceAttributes:
    enabled: true
  kubernetesExtraMetrics:
    enabled: true
    perNode: true
extraConfig:
  processors:
    transform/test:
      error_mode: silent
      trace_statements:
      - context: span
        statements:
        - set(attributes["http.response.status_code"], attributes["http.status_code"]) where attributes["http.response.status_code"] == nil
  service:
    pipelines:
      traces:
        processors:
        - transform/test
