{{- if and .Values.networkExplorer.enabled .Values.networkExplorer.cloudCollector.enabled .Values.networkExplorer.cloudCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector-cloud-collector.serviceAccountName" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- with .Values.networkExplorer.cloudCollector.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
