{{- if and .Values.networkExplorer.enabled .Values.networkExplorer.k8sCollector.enabled .Values.networkExplorer.k8sCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector-k8s-collector.serviceAccountName" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
{{- end -}}
