mode: daemonset
global:
  image: busybox:latest
initContainers:
  - name: test
    command:
      - cp
    args:
      - /bin/sleep
      - /test/sleep
    image: "{{ .Values.global.image }}"
    volumeMounts:
      - name: test
        mountPath: /test

extraVolumesMap:
  test:
    emptyDir: {}

extraVolumeMountsMap:
  test:
    mountPath: /test

lifecycleHooks:
  preStop:
    exec:
      command:
      - /test/sleep
      - "5"

