{{- if and .Values.podMonitor.enabled .Values.podMonitor.metricsEndpoints }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "opentelemetry-ebpf-profiler.fullname" . }}-agent
  namespace: {{ template "opentelemetry-ebpf-profiler.namespace" . }}
  labels:
    {{- include "opentelemetry-ebpf-profiler.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.podMonitor.extraLabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "opentelemetry-ebpf-profiler.selectorLabels" . | nindent 6 }}
      {{- include "opentelemetry-ebpf-profiler.component" . | nindent 6 }}
  {{- if .Values.podMonitor.targetLabels }}
  podTargetLabels:
  {{- toYaml .Values.podMonitor.targetLabels | nindent 2 }}
  {{- end }}
  podMetricsEndpoints:
  {{- toYaml .Values.podMonitor.metricsEndpoints | nindent 2 }}
{{- end }}
