{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-ebpf-profiler.serviceAccountName" . }}
  namespace: {{ template "opentelemetry-ebpf-profiler.namespace" . }}
  labels:
    {{- include "opentelemetry-ebpf-profiler.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
{{ end }}
