mode: daemonset

distribution: gke

presets:
  kubernetesApiServerMetrics:
    enabled: true
    dns:
      enabled: true

config:
  exporters:
    debug:
      verbosity: detailed

  service:
    pipelines:
      metrics:
        exporters:
          - debug

resources:
  limits:
    cpu: 100m
    memory: 200M
