mode: daemonset

presets:
  profilesCollection:
    enabled: true
  coralogixExporter:
    enabled: true
    pipelines: ["all"]
    privateKey: ${env:CORALOGIX_PRIVATE_KEY}
  prometheusAnnotationDiscovery:
    enabled: true
    observePods: true
    observeServices: true
    enableServiceRule: true
  pprofReceiver:
    pull:
      enabled: true
      nodeLocal: true

command:
  extraArgs: ["--feature-gates=+service.profilesSupport"]

resources:
  limits:
    cpu: 100m
    memory: 200M
