mode: daemonset
global:
  domain: coralogix.com

replicaCount: 1
presets:
  metadata:
    enabled: true
    clusterName: "production"
    integrationName: "coralogix-integration-helm"
  hostMetrics:
    enabled: true
  hostEntityEvents:
    enabled: true
  fleetManagement:
    enabled: true
    agentType: "agent"
    clusterName: "test"
    integrationID: "test"
resources:
  limits:
    cpu: 2
    memory: 4Gi

