global:
  domain: "eu2.coralogix.com"
  clusterName: "production"
  defaultApplicationName: otel
  defaultSubsystemName: integration

mode: daemonset

presets:
  ebpfProfiler:
    enabled: true
  fleetManagement:
    enabled: true
    agentType: "agent"
    supervisor:
      enabled: true
      imageVersion: 0.5.0
  coralogixExporter:
    enabled: true
    pipeline: all
    privateKey: ${env:CORALOGIX_PRIVATE_KEY}
