mode: deployment

presets:
  profilesCollection:
    enabled: true
  coralogixExporter:
    enabled: true
    pipelines: ["all"]
    privateKey: ${env:CORALOGIX_PRIVATE_KEY}
  pprofReceiver:
    push:
      enabled: true

command:
  extraArgs: ["--feature-gates=+service.profilesSupport"]

resources:
  limits:
    cpu: 100m
    memory: 200M
