mode: daemonset
global:
  domain: coralogix.com
  defaultApplicationName: otel
  defaultSubsystemName: integration
  version: "1.0"

presets:
  coralogixExporter:
    enabled: true
    privateKey: ${env:CORALOGIX_PRIVATE_KEY}
