mode: statefulset
generateCRD: true

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    storeCheckpoints: true
  hostMetrics:
    enabled: true

configMap:
  create: false

serviceAccount:
  create: false

resources:
  limits:
    cpu: 100m
    memory: 200M