mode: daemonset
hostNetwork: true
distribution: standalone
presets:
  hostMetrics:
    enabled: true
    process:
      enabled: true
  collectorMetrics:
    enabled: true
    scrapeInterval: "30s"
  journaldReceiver:
    enabled: true
