{{- if and .Values.networkExplorer.enabled .Values.networkExplorer.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opentelemetry-collector-kernel-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - {{ include "opentelemetry-collector-kernel-collector.fullname" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end -}}
