global:
  domain: "eu2.coralogix.com"
  clusterName: "douglas-kind-test"
  defaultApplicationName: otel
  defaultSubsystemName: integration
  version: "1.0"

image:
  tag: 0.129.1

command:
  name: opampsupervisor

mode: daemonset
extraVolumes:
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id

extraVolumeMounts:
  - mountPath: /etc/machine-id
    mountPropagation: HostToContainer
    name: etcmachineid
    readOnly: true

presets:
  coralogixExporter:
    enabled: true
    privateKey: ${env:CORALOGIX_PRIVATE_KEY}
  batch:
    enabled: true
  fleetManagement:
    enabled: true
    agentType: "agent"
    supervisor:
      enabled: true
  k8sResourceAttributes:
    enabled: true
  collectorMetrics:
    enabled: true
  resourceDetection:
    enabled: true
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    extraFilelogOperators:
      - type: recombine
        combine_field: body
        source_identifier: attributes["log.file.path"]
        is_first_entry: body matches "^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}|[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})"
    multilineConfigs:
      - namespaceName:
          value: kube-system
        podName:
          value: app-.*
          useRegex: true
        containerName:
          value: http
        firstEntryRegex: ^[^\s].*
        combineWith: ""
      - namespaceName:
          value: default
        podName:
          value: app-.*
          useRegex: true
        firstEntryRegex: ^[^\s].*
        combineWith: ""
      - namespaceName:
          value: test
        firstEntryRegex: ^[^\s].*
        combineWith: ""
  headSampling:
    enabled: true
  kubernetesAttributes:
    enabled: true
  reduceResourceAttributes:
    enabled: true
  kubernetesExtraMetrics:
    enabled: true
    perNode: true
extraConfig:
  processors:
    transform/test:
      error_mode: silent
      trace_statements:
        - context: span
          statements:
            - set(attributes["http.response.status_code"], attributes["http.status_code"]) where attributes["http.response.status_code"] == nil
  service:
    pipelines:
      traces:
        processors:
          - transform/test
