mode: daemonset

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    extraFilelogOperators:
    - type: recombine
      combine_field: body
      source_identifier: attributes["log.file.path"]
      is_first_entry: body matches "^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}|[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})"

