mode: deployment

presets:
  kubernetesAttributes:
    enabled: true

config:
  exporters:
    coralogix:
      application_name: 'otel'
      domain: 'coralogix.com'
    debug: {}
  processors:
    batch:
      send_batch_max_size: 2048
      send_batch_size: 1024
      timeout: 1s
    routing:
      default_exporters:
        - coralogix
      table:
        - exporters:
            - debug
          statement: route() where resource.attributes["team"] == "debug"
  service:
    pipelines:
      traces:
        processors:
          - resource
          - batch
          - routing
