mode: deployment

presets:
  metadata:
    enabled: true
    clusterName: "production"
    integrationName: "coralogix-integration-helm"

config:
  service:
    pipelines:
      traces:
        processors:
          - resource
          - batch

