{{- if .Values.service.enabled }}
{{- $root := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "obi.fullname" . }}
  namespace: {{ include "obi.namespace" .}}
  labels:
    {{- include "obi.labels" . | nindent 4 }}
    app.kubernetes.io/component: networking
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $root }}
  {{- end }}
spec:
  {{- if (or (eq .Values.service.type "ClusterIP") (empty .Values.service.type)) }}
  type: ClusterIP
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- else if eq .Values.service.type "LoadBalancer" }}
  type: LoadBalancer
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- $metricsPort := int (.Values.service.targetPort | default ((.Values.config.data).prometheus_export).port | default 0) }}
  {{- $internalMetricsPort := int (.Values.service.internalMetrics.targetPort | default ((.Values.config.data.internal_metrics).prometheus).port | default 0) }}
  ports:
    {{- if $metricsPort }}
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ $metricsPort }}
      {{- with .Values.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- end }}
    {{- if and $internalMetricsPort (ne $internalMetricsPort $metricsPort) }}
    - name: {{ .Values.service.internalMetrics.portName }}
      port: {{ .Values.service.internalMetrics.port }}
      protocol: TCP
      targetPort: {{ $internalMetricsPort }}
      {{- with .Values.service.internalMetrics.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.internalMetrics.nodePort))) }}
      nodePort: {{ .Values.service.internalMetrics.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "obi.selectorLabels" . | nindent 4 }}
{{- end }}
