{{- if and .Values.service.enabled .Values.serviceMonitor.enabled .Values.config.data.prometheus_export }}
{{- $root := . }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "obi.fullname" . }}
  namespace: {{ include "obi.namespace" .}}
  labels:
    {{- include "obi.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $root }}
  {{- end }}
spec:
  {{- $metricsPort := int (.Values.service.targetPort | default ((.Values.config.data).prometheus_export).port | default 0) }}
  {{- $internalMetricsPort := int (.Values.service.internalMetrics.targetPort | default ((.Values.config.data.internal_metrics).prometheus).port | default 0) }}
  endpoints:
    {{- if $metricsPort }}
    - port: {{ .Values.service.portName }}
      path: {{ ((.Values.config.data).prometheus_export).path | default "/metrics" }}
      scheme: http
      {{- with ((.Values.serviceMonitor).metrics).endpoint }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if and $internalMetricsPort (ne $internalMetricsPort $metricsPort) }}
    - port: {{ .Values.service.internalMetrics.portName }}
      path: {{ ((.Values.config.data.internal_metrics).prometheus).path | default "/metrics" }}
      scheme: http
      {{- with ((.Values.serviceMonitor).internalMetrics).endpoint }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel | default (include "obi.fullname" .) }}
  selector:
    matchLabels:
      {{- include "obi.labels" . | nindent 6 }}
      {{- with .Values.service.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
