mode: deployment

resources:
  limits:
    cpu: 100m
    memory: 200M

configMap:
  create: false

command:
  name: otelcol-contrib
  extraArgs: ["--config=/conf/config.yaml"]

extraVolumes:
  custom-otelcol-configmap:
    configMap:
      name: custom-otel-collector-config
      items:
        - key: config
          path: config.yaml
      defaultMode: 420
extraVolumeMounts:
  custom-otelcol-configmap:
    mountPath: /conf/config.yaml

