mode: daemonset

presets:
  loadBalancing:
    enabled: true
    routingKey: "service"
    hostname: "localhost"
    pipelines: ["traces","profiles","metrics"]
  headSampling:
    enabled: true
  batch:
    enabled: true
  profilesCollection:
    enabled: true

    