mode: deployment

presets:
  loadBalancing:
    enabled: true
    routingKey: "traceID"
    hostname: "coralogix-opentelemetry-gateway"

config:
  service:
    pipelines:
      traces:
        processors:
          - resource
          - batch
