mode: deployment

presets:
  loadBalancing:
    enabled: true
    routingKey: "traceID"
    hostname: "coralogix-opentelemetry-gateway"
  headSampling:
    enabled: true

config:
  service:
    pipelines:
      traces:
        processors:
          - resource
          - batch
