mode: deployment

presets:
  loadBalancing:
    enabled: true
    routingKey: "service"
    k8s:
      enabled: true
      service: lb-svc.kube-public
      ports:
        - 15317
        - 16317
      timeout: 5s
  headSampling:
    enabled: true
