mode: deployment

replicaCount: 1
presets:
  kubernetesResources:
    enabled: true
    periodicCollection:
      enabled: false
    filterStatements:
      - body["kind"] == "Service"
resources:
  limits:
    cpu: 2
    memory: 4Gi

