mode: deployment

replicaCount: 1
presets:
  kubernetesResources:
    enabled: true
    dropManagedFields:
      enabled: true
    periodicCollection:
      enabled: false
    filterStatements:
      - body["kind"] == "Service"
    transformStatements:
      # Change every string value ≥257 chars to the literal "REDACTED"
      - replace_all_patterns(log.attributes, "value", "^(?s).{257,}$", "REDACTED")
resources:
  limits:
    cpu: 2
    memory: 4Gi

